Expanded riddle component
ua-dev-front/solve-the-riddle pull request #25
Opened 2023-06-30 06:48 UTC by Kupriienko

2023-06-30 07:47 UTC, danmysak requested changes

2023-06-30 07:47 UTC, danmysak commented on frontend/src/Riddles/index.tsx
>  }
Загальні зауваження:
1) Задій анімацію про розгортанні / згортанні частини з полем для відповіді.
2) Додай, власне, логіку перевірки.

2023-07-03 13:16 UTC, danmysak requested changes

2023-07-03 13:16 UTC, danmysak commented on frontend/src/Riddles/index.tsx
>  }
Добре!

Утім, анімація зараз працює неідеально. Спробуй сповільнити все у 10 разів і поспостерігай, що відбувається. Це явно не зовсім те, що хотілося б бачити: усе має відбуватися плавно, без стрибків.

2023-07-05 08:55 UTC, danmysak requested changes

2023-07-05 08:55 UTC, danmysak commented on frontend/src/Riddles/index.tsx
>  }
Поверховим тестуванням виявив ще три проблеми:

1) Поля для введення невидимі, але наявні на сторінці, навіть коли згорнуті: коли наводиш на них курсор, він перетворюється на рисочку. Можливо, тобі допоможе `visibility: hidden`.

2) Кнопка у неактивному стані, хоч і напівпрозора, все одно натискається. Схоже, ти не виставив їй `disabled`.

3) Під час завантаження загадок було б непогано, щоб ти так само малював спінер. Для тестування цього скористайся DevTools: Network → Slow 3G (замість No throttling).

2023-07-07 18:02 UTC, danmysak requested changes
Тепер виглядає дуже добре, молодець!
Але робота ще є.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Button/styles.css
> +    pointer-events: none;
Цим рядочком ти фактично усуваєш небажані наслідки неправильного підходу, але краще було б виправити сам підхід. А саме — узагалі не присвоювати неактивній кнопці підсвічування на ховер.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +const localURL = 'http://127.0.0.1:5000/verifyAnswer?';
Винеси цю адресу у змінні оточення. Якщо потрібне пояснення, чому так краще, або просто забулося, що воно таке, кажи.

Крім того, чому `localURL`? Ти ж потім заміниш на справжню адресу, а ім’я змінної лишиться тим самим...

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +    const buttonText = isExpanded ? 'ah, forget it!' : 'take a guess';
Якщо відповідь правильна, то напис `ah, forget it!` втрачає сенс.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                />
Було б добре, якби форма надсилалася по натисканні Enter.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                <AnswerIndicator indicator={indicator} onClick={() => verify(id)} disabled={answer.length === 0} />
Опрацюй ще випадки, коли введений рядок починається або закінчується на пробіли, зокрема повністю з них складається.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                           if (indicator === IndicatorType.Cross) {
А якщо користувач раніше ввів правильну відповідь, а тепер її міняє?..

Пропоную після виставлення правильної відповіді робити і саме поле неактивним. А також, щоб користувач не міг змінити відповідь, поки ми її перевіряємо (якщо інтернет повільний), робити поле неактивним і під час перевірки.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +  margin-left: calc(100% - 110px);
Магічні константи! Треба якось інакше...

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +  transition: opacity 0.2s ease, height 0.3s ease-out, visibility 0s linear 0.3s;;
Подвійна крапка з комою.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +  width: 95%;
Ці дві властивості теж виглядають доволі підозріло: по-перше, чи не мало бути 96%? По-друге, вони залежать одна від одної. Спробуй уникнути цієї залежності або в крайньому випадку скористайся змінними.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddles/index.tsx
> +const localURL = 'http://127.0.0.1:5000/';
Тут такого теж не має лишитися, звичайно.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddles/index.tsx
> +    const [data, setData] = useState([]);
Семантично тут не порожній масив, а `null`: порожній масив означав би, що загадки вже завантажилися, просто їх виявилося нуль.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddles/index.tsx
> +            let actualData = await response.json();
Чому `let`?

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddles/index.tsx
> +                <img src={Preloader} alt={"Loading..."} className="riddles_preloader" />
Фігурні дужки у `alt` не потрібні.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddles/index.tsx
> +                data.map((riddle) => (
Елегантніше буде деструктуризувати аргумент `riddle`.

2023-07-07 18:02 UTC, danmysak commented on frontend/src/Riddles/styles.css
> +  transform: translate(-50%, -50%);
Без зайвої потреби `position: fixed` і `transform` не використовуємо: вони можуть дуже просто зламатися при інших розмірах екрана. Тут можна обійтися більш традиційними способами.

2023-07-11 12:53 UTC, danmysak requested changes

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Input/index.tsx
> +import React from "react";
1) Порядок імпортів.
2) Лапки.

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +import AnswerIndicator, {IndicatorType} from '../AnswerIndicator';
Тут ти ці пробіли поприбирав, а десь — ні. Коли міняєш стиль коду, користуйся пошуком.

Але пропоную все ж таки скрізь ці пробіли залишати. Це дещо більш стандартний варіант.

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +        : indicator === IndicatorType.Checkmark ?  'view answer' : 'take a guess';
1) Очевидно, енам `IndicatorType` почав виконувати ширші функції, ніж передбачає його ім’я. Перейменуй на щось таке, що краще відображатиме значення й призначення цієї змінної.

2) Вкладений тернарний оператор зазвичай не використовують, бо це важко сприймати. Скористайся функцією зі `switch`ем або об’єктом / об’єктами, які відображатимуть значення енаму на подібні написи.

3) У тебе в коді подвійний пробіл. Будь уважним та/або налаштуй середовище, щоб воно підкреслювало подібні тривіальні проблеми.

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +            `${process.env.REACT_APP_UNSPLASH_KEY}/verifyAnswer?` + new URLSearchParams({
Чому змінна оточення має таку дивну назву (я про частинку `UNSPLASH_KEY`)?

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +        setDisabled(response['correct']);
Типізуй повернений результат і звертайся до поля як `response.correct`. Те саме стосується і запиту на отримання списку всіх загадок.

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                           if (event.key === "Enter") {
1) Лапки...
2) Треба якось синхронізувати зі станом кнопки: щоб запит не надсилався, якщо, наприклад, поле порожнє. В ідеалі і сам код `verify(id)` дублюватися не має...

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                    answer.trim() === ''}/>
Ці умови надлишкові.

2023-07-11 12:53 UTC, danmysak commented on frontend/.gitignore
> +.env
Те, що додав сюди `.env`, —  молодець. Але в таких випадках також добре додавати в репозиторій файл `.env.example`, у якому прописати якісь умовні значення для змінних, щоб іншим розробникам (або зараз, наприклад, мені) не доводилося шукати по коду, як мають називатися змінні і що значити.

2023-07-11 12:53 UTC, danmysak commented on frontend/src/Riddles/styles.css
> +  height: 100vh;
Тепер у тебе сторінка займає висоту меню + 100vh, відповідно з’являється вертикальне прокручування. Неідеально.

Але спробуй обійтися і без магічних констант.

2023-07-11 12:55 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                <AnswerIndicator indicator={indicator} onClick={() => verify(id)} disabled={answer.length === 0} />
Ти опрацював лише частину «зокрема повністю з них складається».

2023-07-16 17:15 UTC, danmysak requested changes

2023-07-16 17:15 UTC, danmysak commented on frontend/src/AnswerIndicator/index.tsx
>      Button
Нова назва непогана. Але тоді і пункти енаму потрібно дещо підредагувати.

2023-07-16 17:15 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +import AnswerIndicator, {AnswerStatus} from '../AnswerIndicator';
Усе одно по-різному розставлені фігурні дужки. Прошу, будь уважнішим і користуйся пошуком.

2023-07-16 17:15 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +    }
Основна альтернатива тернарному оператору (яку слід використовувати, щоб не вкладати два тернарних один в одний) — `if`/`else`. Конструкція `switch` набуває сенсу, коли є щонайменше три різних варіанти, і то інколи є сенс скористатися `if` / `else if` / `else`.

2023-07-16 17:15 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                           if (event.key === 'Enter' && answer.trim() !== '') {
У тебе зараз ця умова фактично дублюється в коді. Якщо ти захочеш її змінити чи доповнити, то в одному з двох місць можеш забути це зробити. Тож треба позбутися дублювання.

2023-07-16 17:15 UTC, danmysak commented on frontend/src/Riddles/index.tsx
> +                    <img src={Preloader} alt="Loading..." className="preloader"/>
1) Назва цього класу не відповідає стандартним правилам найменувань.
2) Він узагалі потрібен?

2023-07-16 17:15 UTC, danmysak commented on frontend/src/Riddles/styles.css
> +  height: 90vh;
Тепер виходить магічна константа: якщо вигляд меню зміниться, сторінка може сповзти чи навпаки не дотягувати до висоти екрана.

2023-07-16 17:15 UTC, danmysak commented on frontend/src/Riddles/styles.css
> +
Для чого ці додаткові порожні рядки?

2023-07-19 13:26 UTC, danmysak requested changes

2023-07-19 13:26 UTC, danmysak commented on frontend/src/AnswerIndicator/index.tsx
> +interface UnverifiedProps {
Автоматична заміна зіграла тут злий жарт.

2023-07-19 13:26 UTC, danmysak commented on frontend/src/App.css
> +    height: 100vh;
`vh` без потреби теж краще не використовувати (щоб не втрачати універсальності компонента, тобто його здатності працювати в різних контекстах). Відсотки тобі цілком підійдуть. Можливо, правда, доведеться виставити також висоту елементам `html` і `body`.

2023-07-19 13:26 UTC, danmysak commented on frontend/src/Riddles/styles.css
> +        width: calc(100% - 72px);
До речі, нагадай, будь ласка, для чого це потрібно.

2023-07-22 11:56 UTC, Kupriienko commented on frontend/src/Riddles/styles.css
> +        width: calc(100% - 72px);
Це допомагає забезпечити оптимальний дизайн для малих екранів, дозволяючи елементам займати менше місця горизонтально.

2023-07-24 12:29 UTC, danmysak requested changes

2023-07-24 12:29 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +    function isAnswerBlank() {
Коли казав у слеку «правильно назвати функцію», то мав на увазі якраз-таки, що функцію треба назвати відповідно до того, з якою метою ти її створюєш. Ця функція з’явилася для того, щоб не дублювати логіку перевірки, чи валідна відповідь (те, чи порожня відповідь, може бути лише частиною такої перевірки). Отже, правильною була якраз стара назва.

2023-07-26 05:54 UTC, danmysak approved these changes
Шик!

2023-07-28 11:20 UTC, merged