Coloring riddles
ua-dev-front/solve-the-riddle pull request #26
Opened 2023-07-28 14:07 UTC by Kupriienko

2023-07-29 06:42 UTC, danmysak requested changes

2023-07-29 06:42 UTC, danmysak commented on frontend/src/Riddle/styles.css
>  .expanded .riddle_block {
1) У дизайні фон поля для введення відповіді залишається білим.
2) У тебе зараз анімований перехід між кольорами в якихось випадках спрацьовує, а в якихось ні. Забезпеч, щоб перехід між кольорами був плавним завжди.

2023-08-04 04:17 UTC, danmysak requested changes

2023-08-04 04:17 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                }, 300);
Ні присвоєння класів через звичайний JavaScript, ні тим більше використання таймаутів для цього в реактівському коді бути не має — крім крайніх випадків.

Для чого саме це тобі знадобилося? Хіба без цього — просто з трьома різними класами для трьох різних кольорів — не вийде?

2023-08-04 11:34 UTC, Kupriienko commented on frontend/src/Riddle/index.tsx
> +                }, 300);
Забув видалити цей код. Це не мало б попасти сюди.

2023-08-04 16:21 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +                }, 300);
Тоді нагадаю: перед тим, як запитувати у колеги рев’ю, переглянь свій код сам. Не перекладай цю частину роботи на інших.

2023-08-04 16:25 UTC, danmysak requested changes

2023-08-04 16:25 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +    }`;
Вкладені тернарні оператори, як пам’ятаєш, не використовуємо: такий код складно прочитати і оцінити на правильність.

2023-08-04 16:25 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +    console.log(riddleClassName)
Цього тут теж бути не мало.

2023-08-04 16:25 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +        <div className={`riddle ${riddleClassName}`}>
За BEM’ом (правила найменування класів, яким ми користуємося) це мало би бути не `riddle correct`, `riddle expanded` і т. д., а `riddle riddle-correct`, `riddle riddle-expanded` і т. д.

2023-08-06 16:07 UTC, danmysak requested changes

2023-08-06 16:07 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +    }
Це неідеальний варіант сконструювати потрібні класи: рознесений на кілька рядків коду і вразливий до пропущених пробілів після назв класів при модифікації (необхідність проставляти оці пробіли після кожної назви можеш уважати своєрідною дублікацією логіки). Скористайся одним із трьох підходів, позбавлених принаймні частини цих недоліків:

1) Скористайся [інтерполяцією рядків](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals): встав вирази з тернарними операторами прямо в рядок.

2) Сконструюй масив, а не рядок, а потім склей елементи масиву пробілом.

3) Скористайся бібліотекою [classnames](https://www.npmjs.com/package/classnames).

2023-08-06 16:07 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +            <div className={`riddle_block ${isExpanded ? 'riddle-expanded' : ''}`}>
Якщо елемент називається `riddle_block`, то його модифікатор має називатися `riddle_block-expanded` (а не `riddle-expanded`).

2023-08-06 16:07 UTC, danmysak commented on frontend/src/Riddle/index.tsx
> +            <div className={`riddle_answerBlock ${isExpanded ? 'riddle-expanded' : ''}`}
І тут те саме.

2023-08-07 16:01 UTC, danmysak requested changes

2023-08-07 16:01 UTC, danmysak commented on frontend/src/Riddle/index.tsx
>          <div className={`riddle ${riddleClassName}`}>
Визначення потрібних класів у тебе досі займає 11 рядків (із 60-го до 70-го). Зажени їх усі з допомогою інтерполяції у 70-й рядок. Якщо не поміститься в один, розбий на кілька, але акуратних послідовних — щоб це було просто читати.

2023-08-07 16:01 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +.riddle_block.riddle_block-expanded {
Тут і нижче — BEM передбачає, що в селекторах використовуємо тільки один клас. Для того він у собі вже і так містить назву класу базового елемента.

2023-08-08 13:45 UTC, danmysak requested changes
Із кольорами тепер усе добре. Не знаю, чи точно це пов’язано зі змінами саме в цьому PR, але зараз є проблема з анімаціями розкривання/закривання форми для введення відповіді. Сповільни всі анімації в 10 разів і побачиш.

2023-08-17 04:13 UTC, danmysak requested changes

2023-08-17 04:13 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +.riddle_container::before{
Бракує пробілу.

2023-08-17 04:13 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +  transition-delay: 0.01s;
То, може, тоді вже просто прибрати цей перехід?

2023-09-02 19:49 UTC, danmysak requested changes

2023-09-02 19:49 UTC, danmysak commented on frontend/src/Riddle/styles.css
> +  transition: opacity 10.2s ease-out, height 10.3s ease-out, visibility 10.3s linear, padding 10.4s linear;
Не повернув старі значення.

2023-09-10 07:28 UTC, danmysak approved these changes

2023-09-10 18:24 UTC, merged